services:
  bugsink:
    x-miget:
      ram: "1024"
    environment:
      DATABASE_URL: ${{db.url}}
      BEHIND_HTTPS_PROXY: "true"
      CREATE_SUPERUSER: ${CREATE_SUPERUSER:-}
      BASE_URL: ${MIGET_PUBLIC_URL}

  db:
    x-miget:
      managed: postgres
      cpu: "500m"
      ram: "1Gi"
      storage: "5Gi"
