services:
  agent:
    build:
      context: https://github.com/livekit-examples/agent-starter-python.git
    restart: unless-stopped
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL:-ws://livekit:5000}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      ELEVEN_API_KEY: ${ELEVEN_API_KEY:-}
      DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
