services:
  kong:
    x-miget:
      ram: "512"
    environment:
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:?}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:?}

  auth:
    x-miget: { ram: "256", private: true }
    environment:
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      API_EXTERNAL_URL: ${MIGET_PUBLIC_URL}
      SITE_URL: ${MIGET_PUBLIC_URL}

  rest:
    x-miget: { ram: "256", private: true }
    environment:
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

  studio:
    x-miget: { ram: "512", private: true }
    environment:
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      PG_META_CRYPTO_KEY: ${PG_META_CRYPTO_KEY:?}
      SUPABASE_PUBLIC_URL: ${MIGET_PUBLIC_URL}

  meta:
    x-miget: { ram: "256", private: true }
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      PG_META_CRYPTO_KEY: ${PG_META_CRYPTO_KEY:?}

  db:
    x-miget:
      ram: "768"
      private: true
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

volumes:
  dbdata:
    x-miget: { size: "8000", type: RWO }
