services:
  code-server:
    image: codercom/code-server:4.129.0-trixie
    restart: unless-stopped
    command:
      - --bind-addr
      - 0.0.0.0:5000
      - --auth
      - password
    environment:
      PASSWORD: ${PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - workspace:/home/coder

volumes:
  workspace:
