services:
  campfire:
    image: ghcr.io/basecamp/once-campfire:main
    restart: unless-stopped
    environment:
      HTTP_PORT: "5000"
      DISABLE_SSL: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
    ports:
      - "5000:5000"
    volumes:
      - storage:/rails/storage

volumes:
  storage:
