name: actual

services:
  actual:
    image: ghcr.io/actualbudget/actual:26.8.1
    restart: unless-stopped
    environment:
      ACTUAL_PORT: "5000"
    ports:
      - "5000:5000"
    volumes:
      - actualdata:/data

volumes:
  actualdata:
