services:
  mailpit:
    image: axllent/mailpit:v1.30.5
    restart: unless-stopped
    environment:
      MP_UI_BIND_ADDR: 0.0.0.0:5000
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025
      MP_UI_AUTH: ${MP_UI_AUTH}
      MP_DATABASE: /data/mailpit.db
      MP_MAX_MESSAGES: "5000"
    ports:
      - "5000:5000"
      - "1025:1025"
    volumes:
      - mailpitdata:/data

volumes:
  mailpitdata:
