server {
    listen 5000;
    client_max_body_size 100m;

    location /console/api { proxy_pass http://api:5001; include /etc/nginx/proxy-common.conf; }
    location /api         { proxy_pass http://api:5001; include /etc/nginx/proxy-common.conf; }
    location /v1          { proxy_pass http://api:5001; include /etc/nginx/proxy-common.conf; }
    location /files       { proxy_pass http://api:5001; include /etc/nginx/proxy-common.conf; }
    location /e/          { proxy_pass http://plugin-daemon:5002; include /etc/nginx/proxy-common.conf; }
    location /            { proxy_pass http://web:5000;  include /etc/nginx/proxy-common.conf; }
}
