services:
  registry:
    x-miget:
      ram: "256"
    environment:
      REGISTRY_STORAGE_S3_REGION: ${REGISTRY_STORAGE_S3_REGION}
      REGISTRY_STORAGE_S3_REGIONENDPOINT: ${REGISTRY_STORAGE_S3_REGIONENDPOINT}
      REGISTRY_STORAGE_S3_BUCKET: ${REGISTRY_STORAGE_S3_BUCKET}
      REGISTRY_STORAGE_S3_ACCESSKEY: ${REGISTRY_STORAGE_S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${REGISTRY_STORAGE_S3_SECRETKEY}

volumes:
  registrydata:
    x-miget: { size: "10000", type: RWO }
