services:
  registry:
    build: .
    restart: unless-stopped
    environment:
      REGISTRY_AUTH_USER: ${REGISTRY_AUTH_USER:-admin}
      REGISTRY_AUTH_PASSWORD: ${REGISTRY_AUTH_PASSWORD}
      REGISTRY_AUTH_REALM: ${REGISTRY_AUTH_REALM:-Registry}
      REGISTRY_STORAGE_S3_REGION: ${REGISTRY_STORAGE_S3_REGION:-}
      REGISTRY_STORAGE_S3_REGIONENDPOINT: ${REGISTRY_STORAGE_S3_REGIONENDPOINT:-}
      REGISTRY_STORAGE_S3_BUCKET: ${REGISTRY_STORAGE_S3_BUCKET:-}
      REGISTRY_STORAGE_S3_ACCESSKEY: ${REGISTRY_STORAGE_S3_ACCESSKEY:-}
      REGISTRY_STORAGE_S3_SECRETKEY: ${REGISTRY_STORAGE_S3_SECRETKEY:-}
      REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ${REGISTRY_STORAGE_S3_FORCEPATHSTYLE:-true}
    ports:
      - "5000:5000"
    volumes:
      - registrydata:/var/lib/registry

volumes:
  registrydata:
