x-miget:
  variables:
    ANON_KEY:
      derive: hs256_jwt
      from: JWT_SECRET
      claims: { role: anon, iss: supabase, iat: 1700000000, exp: 2000000000 }
    SERVICE_ROLE_KEY:
      derive: hs256_jwt
      from: JWT_SECRET
      claims: { role: service_role, iss: supabase, iat: 1700000000, exp: 2000000000 }

services:
  gateway:
    x-miget:
      ram: "16"
    environment:
      JWT_SECRET: ${JWT_SECRET:?}
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}

  auth:
    x-miget: { ram: "48", private: true }
    environment:
      JWT_SECRET: ${JWT_SECRET:?}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      API_EXTERNAL_URL: ${{gateway.public_url}}
      SITE_URL: ${{gateway.public_url}}

  rest:
    x-miget: { ram: "224", private: true }
    environment:
      JWT_SECRET: ${JWT_SECRET:?}
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      PGRST_SERVER_HOST: "*"

  db:
    x-miget:
      ram: "224"
      private: true
    environment:
      JWT_SECRET: ${JWT_SECRET:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

volumes:
  dbdata:
    x-miget: { size: "4000", type: RWO }
