services:
  directus:
    x-miget:
      ram: "1024"
    environment:
      DB_HOST: ${{db.host}}
      DB_PORT: ${{db.port}}
      DB_DATABASE: ${{db.database}}
      DB_USER: ${{db.username}}
      DB_PASSWORD: ${{db.password}}

  db:
    x-miget:
      managed: postgres
      cpu: "500m"
      ram: "1Gi"
      storage: "5Gi"

volumes:
  uploads:
    x-miget: { size: "5000", type: RWO }
