services:
  agent:
    build: .
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL:-Default}
      AZP_AGENT_NAME: ${AZP_AGENT_NAME:-miget-agent}
    volumes:
      - agentwork:/azp/_work

volumes:
  agentwork:
