services:
  karakeep:
    x-miget:
      ram: "1024"

  meilisearch:
    x-miget:
      ram: "512"
      private: true

  chrome:
    x-miget:
      ram: "512"
      private: true

volumes:
  data:
    x-miget: { size: "10000", type: RWO }
  meili:
    x-miget: { size: "5000", type: RWO }
